[package]
name = "weekly-content-up"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
dotenvy = "0.15.1"
confy = "0.4"
fs_extra = "1.2"